apiVersion: v1
kind: Service
metadata:
  labels:
    run: prometheus
  name: prometheus-lb
  namespace: prometheus
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
