---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo
  namespace: jenkins
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
