apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-server
  name: jenkins
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
  - name: jenkins-http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: jnlp
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins-server
