---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-lb
  namespace: docker-registry
  annotations:
    "kubernetes.io/ingress.class": traefik
    "metallb.universe.tf/ip-allocated-from-pool": default-pool
    "traefik.ingress.kubernetes.io/custom-response-headers": "Access-Control-Allow-Origin:http://registry-ui.k3s.kippel.de||Access-Control-Allow-Methods:GET,POST,OPTIONS||Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range||Access-Control-Expose-Headers:Content-Length,Content-Range"
  labels:
    app: docker-registry
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: docker-registry
  labels:
    run: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:2
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /var/lib/registry
        - name: certs
          mountPath: /certs
        - name: config
          mountPath: /etc/docker/registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: docker-registry
        - name: certs
          secret:
            secretName: docker-registry-tls-cert
        - name: config
          configMap:
            name: docker-registry-config
            optional: false
