apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-lb
  name: longhorn-lb
  namespace: longhorn-system
spec:
  type: LoadBalancer
  ports:
  - name: longhorn-http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: longhorn-ui
