apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-frontend-np
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  type: NodePort
  ports:
  - port: 80
    targetPort: http
